# Generated by Django 5.1 on 2024-08-21 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0004_contestproblem_min_points'),
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='problem',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='feeds', to='competition.contestproblem'),
        ),
    ]
