# Generated by Django 5.1 on 2024-08-19 16:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContestProblem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('problem_id', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('problem_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competition.contestproblem')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competition.participant')),
            ],
        ),
    ]
