# Generated by Django 5.1 on 2024-08-19 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestproblem',
            name='points',
            field=models.IntegerField(default=1000),
        ),
    ]
