# Generated by Django 5.1 on 2024-08-20 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0002_contestproblem_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
