# Generated by Django 5.1 on 2024-08-20 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0003_submission_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestproblem',
            name='min_points',
            field=models.IntegerField(default=100),
        ),
    ]
