# Generated by Django 5.1 on 2024-08-21 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0005_alter_participant_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='user_id',
            new_name='user',
        ),
    ]
