# Generated by Django 5.1 on 2024-11-23 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0007_contestproblem_initial_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
    ]
