# Generated by Django 5.1 on 2024-11-23 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0009_alter_submission_options_alter_submission_score_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['user_id', 'problem_id', 'is_correct'], name='competition_user_id_63a604_idx'),
        ),
    ]
